### ISSUE TITLE
Ticket: Fix CTA Hero Module

### ISSUE THREAD

**Issue by trinitychristiana-eb** [trinitychristiana-eb/task-tracker#73]
- [x] Solve Ticket
   - [Example page](https://www.eventbrite.com/organizer/overview/)
   - Created a page https://www.evbdev.com/organizer/tct-org/
   - Has error Fixing error
   - Start Yak server
   - Go to [wagtail](http://localhost:8000/admin/)
- [x] [Create PR](https://github.com/eventbrite/eb-ui/pull/5408)
- [x] Put PR in #seo-needs-you
- [ ] Get Reviews
   - [x] Delaine
   - [x] Justin
   - [ ] Olivia
- [ ] Merge it
- [ ] Say ready for QA in #seo-needs-you

**Comment by trintiychristiana-eb** [comment]
How to open local wagtail
```
yak dev destination 
```
go to [wagtail](http://localhost:8000/admin)

**Comment by trintiychristiana-eb** [comment]
CSS class number options
```scss
// Size map
$size-map: (
    '0': $spacing-0,
    '1': $spacing-1,
    '2': $spacing-2,
    '3': $spacing-3,
    '4': $spacing-4,
    '5': $spacing-5,
    '6': $spacing-6,
    '8': $spacing-8,
    '10': $spacing-10,
    '12': $spacing-12,
    '14': $spacing-14,
    '16': $spacing-16,
    '18': $spacing-18,
    '20': $spacing-20,
);
```

**Comment by trintiychristiana-eb** [comment]
This Component did not have margin classes for medium-wide and large narrow. 
```tsx
'eds-l-mw-mar-top-14',
'eds-l-ln-mar-top-14',
```

**Comment by trintiychristiana-eb** [comment]
`.eds-l-` responsive size options
```scss
@include small-narrow {
    @include spacing-mapper('sn', 'mar', 'margin');
}

@include small {
    @include spacing-mapper('sm', 'mar', 'margin');
}

@include small-wide {
    @include spacing-mapper('sw', 'mar', 'margin');
}

@include medium-narrow {
    @include spacing-mapper('mn', 'mar', 'margin');
}

@include medium {
    @include spacing-mapper('md', 'mar', 'margin');
}

@include medium-wide {
    @include spacing-mapper('mw', 'mar', 'margin');
}

@include large-narrow {
    @include spacing-mapper('ln', 'mar', 'margin');
}

@include large {
    @include spacing-mapper('lg', 'mar', 'margin');
}

@include large-wide {
    @include spacing-mapper('lw', 'mar', 'margin');
}
```

**Comment by trintiychristiana-eb** [comment]
Remove `'eds-l-sm-mar-top-0',` because this never applies. The default is already 0

/* Option 1 (No margin tops) */
- remove from `ctaHeaderClasses`
```
'eds-l-lg-mar-top-12',
'eds-l-lw-mar-top-12',
```
- add to `ctaHeaderClasses`
```
'eds-l-sw-mar-top-2', // New Width
'eds-l-mn-mar-top-2', // New Width
```

**Comment by trintiychristiana-eb** [comment]
Created a Mix-in that creates classes for
- max-Width
- min-width
- max-height
- min-height
- height in percentage
- width in percentage
- all the above but responsive

### Min/Max Height/Width Syntax
`.eds-[Breakpoint-]<Min/Max><Attribute><Size>`

Parameter | Values
-- | --
Breakpoint (optional) | sn, sm, sw, mn, md, mw, ln, lg, lw
Min/max (required) | min, max
Attribute (required) | w, h => width, height
Size (required) | 0-500 =>$selected-number*$grid-unit


### Height/WIdth Percentage Syntax
`.eds-[Breakpoint-]<Attribute><Percentage>p`

Parameter | Values
-- | --
Breakpoint (optional) | sn, sm, sw, mn, md, mw, ln, lg, lw
Attribute (required) | w, h => width, height
Percentage (required) | 0-100

**Comment by trintiychristiana-eb** [comment]
Ticket Links

[Original Version](https://www.evbqa.com/l/tct-cta-module-test/)

[New Version](https://www.evbqa.com/l/tct-cta-module-test/?version=EB-147274-fix-cta-hero-module)
